import graph

k = 31
s = 'AGCTGGTTGCGCGTCTCCTGCGGCAGCTGCGCAACAGCTTCAAAGTAGTAGCAAATCTGCGCCAGCAAACGGCTGATGTTAATCGAGTTAGCCGAGTTTAACCCTAGCGCCACTTTCAGTTCTTCATCATCAAACGCCTGCTTCACCAGCGCCTGACAGGCATCGAAATCGCCGTCGATGGCAACAGTTTCGATATTGCCGCCCAATGTACAGAACAGTTTTTCTTGCAGTGGACTGATTTTGCCTCGTGGATAGAGGATAACCACTTTCACATTCGGTAAACCGTAGAAAGCATGAGCCACTGCCGCTCCGGTATCACCGGAGGTCGCGGTCAGAATGGTCACTGGCTTATCACCCGCAATATGGGTCAGCATTTGTGCCATAAAGCGACCGCCGAAATCTTTAAATGCCAGCGTTGGCCCGTGGAACAATTCCA'

s = 'AGCTGGTTGCGCGTCTCCTGCGGCAGCTGCGCAACAGCTTCAAAGTAGTAGCAAATCTGCGCCAGCAAACGGCTGATGTTAATCGAGTTAGCCGAGTTTAACCCTAGCGCCACTTTCAGTTCTTCATCATCAAACGCCTGCTTCACCAGCGCCTGACAGGCATCGAAATCGCCGTCGATGGCAACAGTTTCGATATTGCCGCCCAATGTACAGAACAGTTTTTCTTGCAGTGGACTGATTTTGCCTCGTGGATAGAGGATAACCACTTTCACATTCGGTAAACCGTAGAA'
read = s[:100]
graph.Kmer.set_k(k)
km = graph.Kmer(s[:k])

cm = graph.ContigMapper()
bf = graph.BloomFilter()
bf.open('../test/tiny/test.bf')
bf.count()

cm.mapBloomFilter(bf)
print 'trying to fing ', km

raw_input("Press Enter to continue...")

x = cm.findContig(km,read,0)
print x
