#ifndef BFG_COLOREDCDBG_HPP
#define BFG_COLOREDCDBG_HPP

#include <iostream>
#include <random>
#include <unordered_map>
#include <unordered_set>

#include "CompactedDBG.hpp"
#include "DataManager.hpp"

#include "getRSS.h"

/** @file src/ColoredCDBG.hpp
* Interface for the Colored and Compacted de Bruijn graph API.
* Code snippets using this interface are provided in test/snippets.hpp.
*/

/** @struct CCDBG_Build_opt
* @brief Members of this structure are parameters for ColoredCDBG::build, except for:
* - CCDBG_Build_opt::k and CCDBG_Build_opt::g as they must be set in the constructor of the graph.
* - CCDBG_Build_opt::clipTips, CCDBG_Build_opt::deleteIsolated and CCDBG_Build_opt::useMercyKmers are used
* by ColoredCDBG::simplify
* - CCDBG_Build_opt::prefixFilenameOut, CCDBG_Build_opt::outputGFA and CCDBG_Build_opt::outputColors are
* used by ColoredCDBG::write
* Most parameters have default values.
* An example of using such a structure is shown in src/Bifrost.cpp.
* @var CCDBG_Build_opt::reference_mode
* Input are assembled genomes, unitigs or graph files (true), no filtering step performed, all k-mers are used.
* You must not directly build a ColoredCDBG from reads (check README file).
* Default is true.
* @var CCDBG_Build_opt::verbose
* Print information messages during execution if true. Default is false.
* @var CCDBG_Build_opt::clipTips
* Clip short (length < 2k) tips of the graph (not used by ColoredCDBG::build). Default is false.
* @var CCDBG_Build_opt::deleteIsolated
* Remove short (length < 2k) isolated unitigs of the graph (not used by ColoredCDBG::build).
* Default is false.
* @var CCDBG_Build_opt::useMercyKmers
* Keep in the graph low coverage k-mers connecting tips of the graph. Default is false.
* @var CCDBG_Build_opt::k
* Length of k-mers (not used by ColoredCDBG::build). Default is 31.
* @var CCDBG_Build_opt::g
* Length of g-mers, the minimizers, such that g < k (not used by ColoredCDBG::build).
* Default is 23.
* @var CCDBG_Build_opt::nb_threads
* Number of threads to use for building the graph. Default is 1.
* @var CCDBG_Build_opt::read_chunksize
* Number of reads a thread can read and process at a time. Default is 64.
* @var CCDBG_Build_opt::unitig_size
* Maximum length of a unitig. Default is 100000.
* @var CCDBG_Build_opt::nb_unique_kmers
* Estimated number (upper bound) of different k-mers in the input FASTA/FASTQ/GFA files of
* CCDBG_Build_opt::filename_in. Default is KmerStream estimation.
* @var CCDBG_Build_opt::nb_non_unique_kmers
* Estimated number (upper bound) of different k-mers occurring twice or more in the FASTA/FASTQ/GFA
* files of CCDBG_Build_opt::filename_in. Default is KmerStream estimation.
* @var CCDBG_Build_opt::nb_bits_unique_kmers_bf
* Number of Bloom filter bits per k-mer occurring at least once in the FASTA/FASTQ/GFA files of
* CCDBG_Build_opt::filename_in. Default is 14.
* @var CCDBG_Build_opt::nb_bits_non_unique_kmers_bf
* Number of Bloom filter bits per k-mer occurring at least twice in the FASTA/FASTQ/GFA files of
* CCDBG_Build_opt::filename_in. Default is 14.
* @var CCDBG_Build_opt::prefixFilenameOut
* Prefix for the name of the file to which the graph must be written. Mandatory parameter.
* @var CCDBG_Build_opt::inFilenameBBF
* String containing the name of a Bloom filter file that is generated by ColoredCDBG::filter.
* If empty, the filtering step is executed. Otherwise, the Bloom filter is loaded from this file
* and the filtering step is skipped. Default is no input file.
* @var CCDBG_Build_opt::outFilenameBBF
* String containing the name of a Bloom filter file that will be generated by ColoredCDBG::filter.
* If empty, the file is not created. Otherwise, the Bloom filter is written to this file.
* Default is no output file.
* @var CCDBG_Build_opt::filename_seq_in
* vector of strings, each string is the name of a FASTA/FASTQ/GFA file to use for the graph construction.
* Mandatory parameter.
* @var CCDBG_Build_opt::filename_colors_in
* vector of strings, each string is the name of a color set file to use for the graph construction.
* If not empty, colors are loaded in memory from the files. In such case, the color filenames order
* in this vector must match the order of the filenames in CCDBG_Build_opt::filename_seq_in.
* Default is no input color files.
* @var CCDBG_Build_opt::outputGFA
* Boolean indicating if the graph is written to a GFA file (true) or if the unitigs are written to a
* FASTA file (false). Default is true.
* @var CCDBG_Build_opt::outputColors
* Boolean indicating if color sets must be written to disk (true) or not (false). Default is true.
*/
struct CCDBG_Build_opt {

    bool reference_mode;
    bool verbose;

    size_t nb_threads;
    size_t read_chunksize;
    size_t unitig_size;
    size_t nb_unique_kmers;
    size_t nb_non_unique_kmers;
    size_t nb_bits_unique_kmers_bf;
    size_t nb_bits_non_unique_kmers_bf;

    string inFilenameBBF;
    string outFilenameBBF;

    vector<string> filename_seq_in;

    // The following members are not used by CompactedDBG<T>::build
    // but you can set them to use them as parameters for other functions
    // such as CompactedDBG<T>::simplify or CompactedDBG<T>::write.

    vector<string> filename_colors_in;

    size_t k, g;

    bool clipTips;
    bool deleteIsolated;
    bool useMercyKmers;

    bool outputGFA;
    bool outputColors;

    string prefixFilenameOut;

    CCDBG_Build_opt() : nb_threads(1), k(DEFAULT_K), g(DEFAULT_G), nb_unique_kmers(0), nb_non_unique_kmers(0),
                        nb_bits_unique_kmers_bf(14), nb_bits_non_unique_kmers_bf(14), read_chunksize(64),
                        unitig_size(1000000), verbose(false), clipTips(false), deleteIsolated(false), useMercyKmers(false),
                        outputGFA(true), outputColors(true), reference_mode(true), inFilenameBBF(""), outFilenameBBF("") {}

    /** Creates a CDBG_Build_opt (for a CompactedDBG object) from a CCDBG_Build_opt.
    * @return a CDBG_Build_opt
    */
    CDBG_Build_opt getCDBG_Build_opt() const {

        CDBG_Build_opt cdbg_opt;

        cdbg_opt.reference_mode = reference_mode;
        cdbg_opt.filename_in = filename_seq_in;

        cdbg_opt.verbose = verbose;

        cdbg_opt.nb_threads = nb_threads;
        cdbg_opt.read_chunksize = read_chunksize;
        cdbg_opt.unitig_size = unitig_size;
        cdbg_opt.nb_unique_kmers = nb_unique_kmers;
        cdbg_opt.nb_non_unique_kmers = nb_non_unique_kmers;
        cdbg_opt.nb_bits_unique_kmers_bf = nb_bits_unique_kmers_bf;
        cdbg_opt.nb_bits_non_unique_kmers_bf = nb_bits_non_unique_kmers_bf;

        cdbg_opt.inFilenameBBF = inFilenameBBF;
        cdbg_opt.outFilenameBBF = outFilenameBBF;

        cdbg_opt.k = k;
        cdbg_opt.g = g;

        cdbg_opt.clipTips = clipTips;
        cdbg_opt.deleteIsolated = deleteIsolated;
        cdbg_opt.useMercyKmers = useMercyKmers;

        cdbg_opt.outputGFA = outputGFA;

        cdbg_opt.prefixFilenameOut = prefixFilenameOut;

        return cdbg_opt;
    }
};

template<typename U> using UnitigColorMap = UnitigMap<DataAccessor<U>, DataStorage<U>>;
template<typename U> using const_UnitigColorMap = const_UnitigMap<DataAccessor<U>, DataStorage<U>>;

/** @class CCDBG_Data_t
* @brief If data are to be associated with the unitigs of the colored and compacted de Bruijn graph, those data
* must be wrapped into a class that inherits from the abstract class CCDBG_Data_t.
* To associate data of type "MyUnitigData" to unitigs, class MyUnitigData must be declared as follows:
* \code{.cpp}
* class MyUnitigData : public CCDBG_Data_t<MyUnitigData> { ... };
* ...
* ColoredCDBG<MyUnitigData> ccdbg;
* \endcode
* An object of type MyUnitigData represents an instanciation of user data associated to one unitig of the graph.
* CCDBG_Data_t has one template parameter: the type of unitig data ("MyUnitigData").
* Because CCDBG_Data_t is an abstract class, all the methods of the base class (CCDBG_Data_t) must be implemented in
* your wrapper (the derived class, aka MyUnitigData in this example). IMPORTANT: If you do not implement those methods,
* default ones that have no effects will be applied. Do not forget to implement copy and move constructors/destructors
* as well as copy and move assignment operators.
* An example of using such a structure is shown in snippets/test.cpp.
*/
template<typename Unitig_data_t> //Curiously Recurring Template Pattern (CRTP)
class CCDBG_Data_t {

    typedef Unitig_data_t U;

    public:

        /**
        * Clear the data associated with a unitig.
        * @param um_dest is a UnitigColorMap object representing a unitig (the reference sequence of um_dest) for which
        * the data must be cleared. The object calling this function represents the data associated with the reference unitig
        * of um_dest.
        */
        void clear(const UnitigColorMap<U>& um_dest){}

        /**
        * Join data of two unitigs which are going to be concatenated. Specifically, if A is the reference unitig
        * of the UnitigColorMap um_dest and B is the reference unitig of the UnitigColorMap um_src, then after the call to
        * this function, unitigs A and B will be removed and a unitig C = AB will be added to the graph. The object calling
        * this function represents the data to associate with the new unitig C = AB. If um_dest.strand = false,
        * then the reverse-complement of A is going to be used in the concatenation. Reciprocally, if um_src.strand = false,
        * then the reverse-complement of B is going to be used in the concatenation. The data of each unitig can be accessed
        * through the method UnitigColorMap::getData(). The two unitigs A and B are guaranteed to be from the same graph.
        * @param um_dest is a UnitigColorMap object representing a unitig (the reference sequence of the mapping) to which
        * another unitig is going to be appended. The object calling this function represents the data associated with the
        * reference unitig of um_dest.
        * @param um_src is a UnitigColorMap object representing a unitig (and its data) that will be appended at the end of
        * the unitig represented by parameter um_dest.
        */
        void concat(const UnitigColorMap<U>& um_dest, const UnitigColorMap<U>& um_src){}

        /**
        * Merge the data of a sub-unitig B to the data of a sub-unitig A.
        * The object calling this function represents the data associated with the reference unitig of um_dest.
        * The two unitigs A and B are NOT guaranteed to be from the same graph. The data of each unitig can be accessed
        * through the UnitigMap::getData.
        * @param um_dest is a UnitigColorMap object representing a sub-unitig (the mapped sequence of the mapping) A. The object
        * calling this function represents the data associated with the reference unitig of um_dest.
        * @param um_src is a UnitigColorMap object representing a sub-unitig (the mapped sequence of the mapping) for which the
        * data must be merged with the data of sub-unitig B (given by parameter um_dest).
        */
        void merge(const UnitigColorMap<U>& um_dest, const const_UnitigColorMap<U>& um_src){}

        /** Extract data corresponding to a sub-unitig of a unitig A. The extracted sub-unitig, called B in the following, is defined
        * as a mapping to A given by the input UnitigColorMap object um_src. Hence, B = A[um_src.dist, um_src.dist + um_src.len + k - 1]
        * or B = rev(A[um_src.dist, um_src.dist + um_src.len + k - 1]) if um_src.strand == false (B is reverse-complemented). After this
        * function returns, unitig A is deleted from the graph and B is inserted in the graph (along with their data and colors) IF the
        * input parameter last_extraction == true. The object calling this function represents the data associated with sub-unitig B.
        * @param uc_dest is a constant pointer to a UnitigColors object representing the k-mer color sets of colored unitig B.
        * If uc_dest == nullptr, no UnitigColors object will be associated with unitig B.
        * @param um_src is a UnitigColorMap object representing the mapping to a colored unitig A from which a new colored unitig B will be
        * extracted, i.e, B = A[um_src.dist, um_src.dist + um_src.len + k - 1] or B = rev(A[um_src.dist, um_src.dist + um_src.len + k - 1])
        * if um_src.strand == false.
        * @param last_extraction is a boolean indicating if this is the last call to this function on the reference unitig A used for the
        * mapping given by um_src. If last_extraction is true, the reference unitig A of um_src will be removed from the graph right after
        * this function returns. Also, all unitigs B extracted from the reference unitig A, along with their data and colors, will be
        * inserted in the graph.
        */
        void extract(const UnitigColors* uc_dest, const UnitigColorMap<U>& um_src, const bool last_extraction){}

        /** Serialize the data to a string. This function is used when the graph is written to disk in GFA format.
        * If the returned string is not empty, the string is appended to an optional field of the Segment line matching the unitig
        * of this data. If the returned string is empty, no optional field and string are appended to the Segment line matching the
        * unitig of this data.
        */
        string serialize() const { return string(); }
};

/** @class ColoredCDBG
* @brief Represent a Colored and Compacted de Bruijn graph. The class inherits from CompactedDBG
* which means that all public functions available with CompactedDBG are also available with ColoredCDBG.
* \code{.cpp}
* ColoredCDBG<> ccdbg_1; // No unitig data
* ColoredCDBG<void> ccdbg_2; // Equivalent to previous notation
* ColoredCDBG<MyUnitigData> ccdbg_3; // An object of type MyUnitigData will be associated with each unitig (along the colors)
* \endcode
* If data are to be associated with the unitigs, these data must be wrapped into a class that inherits from the abstract class
* CCDBG_Data_t, such as in:
* \code{.cpp}
* class MyUnitigData : public CCDBG_Data_t<MyUnitigData> { ... };
* CompactedDBG<MyUnitigData> cdbg;
* \endcode
* Because CCDBG_Data_t is an abstract class, all the methods of the base class (CCDBG_Data_t) must be implemented in
* your wrapper (the derived class, aka MyUnitigData in this example). IMPORTANT: If you do not implement those methods, default
* ones that have no effects will be applied.
*/
template<typename Unitig_data_t = void>
class ColoredCDBG : public CompactedDBG<DataAccessor<Unitig_data_t>, DataStorage<Unitig_data_t>> {

    static_assert(is_void<Unitig_data_t>::value || is_base_of<CCDBG_Data_t<Unitig_data_t>, Unitig_data_t>::value,
                  "Type Unitig_data_t of data associated with vertices of class ColoredCDBG<Unitig_data_t> must "
                  " be void (no data) or a class extending class CCDBG_Data_t");

    typedef Unitig_data_t U;

    template<typename U> friend class DataAccessor;

    public:

        /** Constructor (set up an empty colored cdBG).
        * @param kmer_length is the length k of k-mers used in the graph (each unitig is of length at least k).
        * @param minimizer_length is the length g of minimizers (g < k) used in the graph.
        */
        ColoredCDBG(int kmer_length = DEFAULT_K, int minimizer_length = DEFAULT_G);

        /** Copy constructor (copy a colored cdBG).
        * This function is expensive in terms of time and memory as the content of a colored and compacted
        * de Bruijn graph is copied. After the call to this function, the same graph exists twice in memory.
        * @param o is a constant reference to the colored and compacted de Bruijn graph to copy.
        */
        ColoredCDBG(const ColoredCDBG& o);

        /** Move constructor (move a colored cdBG).
        * The content of o is moved ("transfered") to a new colored and compacted de Bruijn graph.
        * The colored and compacted de Bruijn graph referenced by o will be empty after the call to this constructor.
        * @param o is a reference on a reference to the colored and compacted de Bruijn graph to move.
        */
        ColoredCDBG(ColoredCDBG&& o);

        /** Copy assignment operator (copy a colored cdBG).
        * This function is expensive in terms of time and memory as the content of a colored and compacted
        * de Bruijn graph is copied.  After the call to this function, the same graph exists twice in memory.
        * @param o is a constant reference to the colored and compacted de Bruijn graph to copy.
        * @return a reference to the colored and compacted de Bruijn which is the copy.
        */
        ColoredCDBG& operator=(const ColoredCDBG& o);

        /** Move assignment operator (move a colored cdBG).
        * The content of o is moved ("transfered") to a new colored and compacted de Bruijn graph.
        * The colored and compacted de Bruijn graph referenced by o will be empty after the call to this operator.
        * @param o is a reference on a reference to the colored and compacted de Bruijn graph to move.
        * @return a reference to the colored and compacted de Bruijn which has (and owns) the content of o.
        */
        ColoredCDBG& operator=(ColoredCDBG&& o);

        /** Equality operator.
        * @return a boolean indicating if two compacted de Bruijn graphs have the same colored unitigs (does not
        * compare the data associated with the unitigs).
        */
        bool operator==(const ColoredCDBG& o) const;

        /** Inequality operator.
        * @return a boolean indicating if two compacted de Bruijn graphs have different colored unitigs (does not
        * compare the data associated with the unitigs).
        */
        inline bool operator!=(const ColoredCDBG& o) const;

        /** Addition assignment operator (merge a colored cdBG).
        * After merging, all unitigs and colors of o have been added to and compacted with the current colored
        * and compacted de Bruijn graph (this). If the unitigs of o had data of type "MyUnitigData" associated,
        * they have been added to the current colored and compacted de Bruijn graph using the functions of the
        * class MyUnitigData which are in base class CCDBG_Data_t<MyUnitigData>. This function is similar to
        * ColoredCDBG::merge except that it uses only one thread while ColoredCDBG::merge can work with multiple
        * threads (number of threads provided as a parameter). Note that if multiple colored and compacted
        * de Bruijn graphs have to be merged, it is more efficient to call ColoredCDBG::merge with a vector of
        * ColoredCDBG as input.
        * @param o is a constant reference to the colored and compacted de Bruijn graph to merge.
        * @return a reference to the current colored and compacted de Bruijn after merging.
        */
        ColoredCDBG& operator+=(const ColoredCDBG& o);

        /** Clear the graph: remove unitigs, user data and colors + reset its parameters.
        */
        void clear();

        /** Build the Colored and compacted de Bruijn graph (only the unitigs).
        * A call to ColoredCDBG::mapColors is required afterwards to map colors to unitigs.
        * @param opt is a structure from which the members are parameters of this function. See CCDBG_Build_opt.
        * @return boolean indicating if the graph has been built successfully.
        */
        bool buildGraph(const CCDBG_Build_opt& opt);

        /** Map the colors to the unitigs. This is done by reading the input files and querying the graph.
        * If a color filename is provided in opt.filename_colors_in, colors are loaded from that file instead.
        * @param opt is a structure from which the members are parameters of this function. See CCDBG_Build_opt.
        * @return boolean indicating if the colors have been mapped successfully.
        */
        bool buildColors(const CCDBG_Build_opt& opt);

        /** Write a colored and compacted de Bruijn graph to disk.
        * @param prefix_output_filename is a string which is the prefix of the filename for the two files that are
        * going to be written to disk. Assuming the prefix is "XXX", two files "XXX.gfa" and "XXX.bfg_colors" will
        * be written to disk.
        * @param nb_threads is the number of threads that can be used to write the graph to disk.
        * @param verbose is a boolean indicating if information message are printed during writing (true) or not (false).
        * @return a boolean indicating if the graph was successfully written.
        */
        bool write(const string& prefix_output_filename, const size_t nb_threads = 1, const bool verbose = false) const;

        /** Read a colored and compacted de Bruijn graph from disk. The graph (in GFA format) must have been produced
        * by Bifrost.
        * @param prefix_input_filename is a string which is the prefix of the filename for the two files that are
        * going to be read from disk. Assuming the prefix is "XXX", two files "XXX.gfa" and "XXX.bfg_colors" will
        * be read from disk.
        * @param nb_threads is the number of threads that can be used to read the graph and its colors from disk.
        * @param verbose is a boolean indicating if information messages are printed during reading (true) or not (false).
        * @return a boolean indicating if the graph was successfully read.
        */
        bool read(const string& prefix_input_filename, const size_t nb_threads = 1, const bool verbose = false);

        /** Merge a colored and compacted de Bruijn graph.
        * After merging, all unitigs and colors of the input graph have been added to and compacted with the current
        * colored and compacted de Bruijn graph (this). If the unitigs of the input graph had data of type "MyUnitigData"
        * associated, they have been added to the current colored and compacted de Bruijn graph using the functions of
        * the class MyUnitigData which are also present in its base class CCDBG_Data_t<MyUnitigData>.
        * Note that if multiple colored and compacted de Bruijn graphs have to be merged, it is more efficient to call
        * ColoredCDBG::merge with a vector of ColoredCDBG as input.
        * @param o is a constant reference to the colored and compacted de Bruijn graph to merge.
        * @param nb_threads is an integer indicating how many threads can be used during the merging.
        * @param verbose is a boolean indicating if information messages must be printed during the execution of the function.
        * @return a boolean indicating if the graph has been successfully merged.
        */
        bool merge(const ColoredCDBG& o, const size_t nb_threads = 1, const bool verbose = false);

        /** Merge and clear a colored and compacted de Bruijn graph.
        * After merging, all unitigs and colors of the input graph have been added to and compacted with the current colored
        * and compacted de Bruijn graph (this). The input graph is cleared before the function returns. If the unitigs of the
        * input graph had data of type "MyUnitigData" associated, they have been added to the current colored and compacted
        * de Bruijn graph using the functions of the class MyUnitigData which are also present in its base class
        * CCDBG_Data_t<MyUnitigData>.
        * Note that if multiple colored and compacted de Bruijn graphs have to be merged, it is more efficient to call
        * ColoredCDBG::merge with a vector of ColoredCDBG as input.
        * @param o is a reference on a reference to the colored and compacted de Bruijn graph to merge. It can be obtained using
        * std::move(). After merging, the graph pointed by o is cleared.
        * @param nb_threads is an integer indicating how many threads can be used during the merging.
        * @param verbose is a boolean indicating if information messages must be printed during the execution of the function.
        * @return a boolean indicating if the graph has been successfully merged.
        */
        bool merge(ColoredCDBG&& o, const size_t nb_threads = 1, const bool verbose = false);

        /** Merge multiple colored and compacted de Bruijn graphs.
        * After merging, all unitigs and colors of the input colored and compacted de Bruijn graphs have been added to and
        * compacted with the current colored and compacted de Bruijn graph (this). If the unitigs had data of type "MyUnitigData"
        * associated, they have been added to the current colored and compacted de Bruijn graph using the functions of the
        * class MyUnitigData which are also present in its base class CCDBG_Data_t<MyUnitigData>.
        * @param v is a constant reference to a vector of colored and compacted de Bruijn graphs to merge.
        * @param nb_threads is an integer indicating how many threads can be used during the merging.
        * @param verbose is a boolean indicating if information messages must be printed during the execution of the function.
        * @return a boolean indicating if the graphs have been successfully merged.
        */
        bool merge(const vector<ColoredCDBG>& v, const size_t nb_threads = 1, const bool verbose = false);

        /** Merge and clear multiple colored and compacted de Bruijn graphs.
        * After merging, all unitigs and colors of the input colored and compacted de Bruijn graphs have been added to and
        * compacted with the current colored and compacted de Bruijn graph (this). The input graphs are cleared before the
        * function returns. If the input unitigs had data of type "MyUnitigData" associated, they have been added to the
        * current colored and compacted de Bruijn graph using the functions of the class MyUnitigData which are also present
        * in its base class CCDBG_Data_t<MyUnitigData>.
        * @param v is a reference on a reference to a vector of colored and compacted de Bruijn graphs to merge.  It can be
        * obtained using std::move(). After merging, the graphs in v are cleared.
        * @param nb_threads is an integer indicating how many threads can be used during the merging.
        * @param verbose is a boolean indicating if information messages must be printed during the execution of the function.
        * @return a boolean indicating if the graphs have been successfully merged.
        */
        bool merge(vector<ColoredCDBG>&& v, const size_t nb_threads = 1, const bool verbose = false);

        /** Get the name of a color. As colors match the input files, the color names match the input filenames.
        * @return a string which is either a color name or an empty string if the color ID is invalid or if the
        * colors have not yet been mapped to the unitigs.
        */
        string getColorName (const size_t color_id) const;

        /** Get the names of all colors. As colors match the input files, the color names match the input filenames.
        * @return a vector of strings for which each string is either a color name or an empty string if the color ID is
        * invalid or if the colors have not yet been mapped to the unitigs.
        */
        vector<string> getColorNames() const;

        /** Get the number of colors in the graph.
        * @return the number of colors in the graph.
        */
        inline size_t getNbColors() const { return this->getData()->getNbColors(); }

        void checkColors(const vector<string>& filename_seq_in) const;

    private:

        void initUnitigColors(const CCDBG_Build_opt& opt, const size_t max_nb_hash = 31);
        void buildUnitigColors(const size_t nb_threads);

        void resizeDataUC(const size_t sz, const size_t nb_threads = 1, const size_t max_nb_hash = 31);

        inline bool readColorSets(const CCDBG_Build_opt& opt){

            return this->getData()->read(opt.filename_colors_in[0], opt.verbose);
        }

        bool invalid;
};

#include "ColoredCDBG.tcc"

#endif
